name: PingTester
description: Get player ping
author: StarTux
version: 0.1
main: com.cavetale.pingtester.PingTesterPlugin
commands:
  getping:
    description: Get player ping
    usage: 'Usage: /<command>'
    permission: pingtester.getping
permissions:
  pingtester.getping:
    description: Get your own ping
    default: true
  pingtester.getping.other:
    description: Get ping of other players
    default: op
