main: com.cavetale.pingtester.PingTesterPlugin
name: PingTester
version: 0.1
api-version: 1.13
description: Get player ping
author: StarTux
website: https://github.com/StarTux/PingTester
depend: []
softdepend: []
commands:
  getping:
    description: Get player ping
    usage: 'Usage: /<command>'
    permission: pingtester.getping
permissions:
  pingtester.getping:
    description: Get your own ping
    default: true
  pingtester.getping.other:
    description: Get ping of other players
    default: op
